controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# TASK
app_find_task:
    path: /task
    controller: App\Task\Infrastructure\Controller\TaskController::findTask
